mqtt:
  broker: "tcp://homeassistant.fullelove.lan:1883"
  client_id: "frigate-stitcher"
  user: "frigate"
  password: "frigate"
  frigate_events_topic: "frigate/events"
  reviews_publish_topic: "frigate_stitcher/reviews"

frigate:
  url: "http://micro01-docker01:5000"

profiles:
  - name: "car_port_security"
    cameras:
      - "CarPort"
      - "CarPortDoorbell"
    objects:
      - "person"
    gap: 30

  - name: "office"
    cameras:
      - "Office"
    objects:
      - "person"
    gap: 30
  # - name: "backyard_watch"
  #   cameras:
  #     - "backyard"
  #   objects:
  #     - "person"
  #   gap: 15
