mqtt:
  broker: "tcp://homeassistant.fullelove.lan:1883"
  client_id: "frigate-custom-reviews"
  user: "frigate"
  password: "frigate"
  frigate_events_topic: "frigate/events"
  reviews_publish_topic: "frigate_custom_reviews/reviews"

frigate:
  url: "http://micro01-docker01:5000"

publish_updates: true
event_timeout: 300

profiles:
  - name: "Car Port"
    cameras:
      - "CarPort"
      - "CarPortDoorbell"
    labels:
      - "person"
    required_zones:
      - "Car_Port"
    gap: 30

  - name: "Office"
    cameras:
      - "Office"
    labels:
      - "person"
    gap: 30

  - name: "Garage"
    cameras:
      - "Garage"
    labels:
      - "person"
    gap: 30

  - name: "Outside"
    cameras:
      - Deck
      - Patio
    labels:
      - person